name: Fullstack Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install backend dependencies
        run: npm install

      - name: eslint check
        run: npm run lint

      - name: build backend
        run: npm run build
